master:
  image: redis
  ports:
    - "16379:6379"
slave:
  image: redis
  command: redis-server --slaveof redis-master 6379
  links:
    - master:redis-master
  ports:
    - "16380:6379"
sentinel:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000
  links:
    - master:redis-master
    - slave
  ports:
    - "16381:6379"
